version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
  app:
    build: ./rails
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/src/app
volumes:
  data-volume:
    driver: local